### PR TITLE
DONT MERGE YET : Added better folder structure + code to remove on and off

### PR DESCRIPTION
**Pull request by RobertJGabriel**
@antijingoist Hi,

This is code to add a switch to turn it on and off at the person will :)
Also added a folder order assets/css etc 

Not ready just yet but feedback if you want something like this please let me know cause mine dyslexic myself

### CODE REVIEW

**Comment by RobertJGabriel** [comment]
@antijingoist Also I know its jumping the gun , but if you need someone to help with managing and updating im more then happy :)

**Comment by antijingoist** [comment]
This is guaranteed to cut down on the number of emails I have to respond to once everyone updates. 

I'll run some tests and push it out as soon as I can. Added you as a collaborator also. :)

**Comment by antijingoist** [comment]
Now that I've actually read you're comment, I'll hold off on pushing it to the store until its complete. :D

**Comment by RobertJGabriel** [comment]
@antijingoist Amazing, thank you  :D I will finish the code tonight

**Pull request merged**
